'''[bài 5 cách 1]'''
chuoi_so = input('nhập một chuỗi số nguyên:')
s1 = chuoi_so.count("1")
s2 = chuoi_so.count("2")
s3 = chuoi_so.count("3")
s4 = chuoi_so.count("4")
s5 = chuoi_so.count("5")
s6 = chuoi_so.count("6")
s7 = chuoi_so.count("7")
s8 = chuoi_so.count("8")
s9 = chuoi_so.count("9")
tong = 1*s1+ 2*s2+ 3*s3+ 4*s4+ 5*s5+ 6*s6+ 7*s7+ 8*s8+ 9*s9
so_lon_nhat = max(chuoi_so)
print('tổng của các phần tử số:',tong)
print('số lớn nhất trong chuỗi là:',so_lon_nhat)
